#!/usr/bin/env bash
# Bash script that displays "to infinity and beyond" indefinitely
#+ and "I am invincible!!!" when receiving a SIGTERM signal

trap "echo I am invincible!!!" SIGTERM

while (true)
do
	echo "to infinity and beyond"
	sleep 2
done
