#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line

while ((n<10))
do
	if ((n == 9))
	then
		echo "Hi"
	fi
	echo "Best School"
	((n+=1))
done
